# Generated by Django 5.0.6 on 2024-07-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_rename_dortor_review_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='meet_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
